ProxyPass /api http://127.0.0.1:13101/api retry=0 timeout=60
ProxyPassReverse /api http://127.0.0.1:13101/api

ProxyPass /uploads http://127.0.0.1:13101/uploads retry=0 timeout=60
ProxyPassReverse /uploads http://127.0.0.1:13101/uploads
